# Generated by Django 3.0.14 on 2023-02-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0004_employee_hra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='hra',
            field=models.IntegerField(default=10000),
        ),
    ]
